[project]
title = "Ethan's Project"
version = "0.1.0"
port = 8501
slug = "{project_slug}"
entrypoint = "hello.py"

[branding]
name = "Preswald Project"
logo = "images/newlogo.png"
favicon = "images/images.png"
primaryColor = "#ADD8E6"

[data.my_dataset]
type = "csv"
path = "data/my_dataset.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 